default: java

properties:
  BUILD_DIR: 'build'
  JAVA_SRC:  'src'
  JAVA_TST:  'test'
  CLASS_DIR: '#{BUILD_DIR}/classes'
  CLASS_TST: '#{BUILD_DIR}/test'
  JAVA_MAIN: 'casa.Main'

targets:

  compile:
    doc: 'Compile java source files'
    steps:
    - javac:  '**/*.java'
      source: '#{JAVA_SRC}'
      dest:   '#{CLASS_DIR}'

  java:
    doc: 'Run java program'
    depends: compile
    steps:
    - classpath: 'classpath'
      classes:   '#{CLASS_DIR}'
    - java: '#{JAVA_MAIN}'
      cp:   '#{classpath}'

  junit:
    doc: 'Run Junit tests'
    steps:
    # compile java test classes
    - classpath: 'classpath'
      classes:   '#{CLASS_DIR}'
      jars:      'lib/*.jar'
    - javac:  '**/*.java'
      source: '#{JAVA_TST}'
      cp:     '#{classpath}'
      dest:   '#{CLASS_TST}'
    # run junit on test class
    - classpath: 'classpath'
      classes:   ['#{CLASS_DIR}', '#{CLASS_TST}']
      jars:      'lib/*.jar'
    - java: 'org.junit.runner.JUnitCore'
      cp:   '#{classpath}'
      args: '#{JAVA_MAIN}Test'

  clean:
    doc: 'Clean generated files'
    steps:
    - delete: '#{BUILD_DIR}'
