default: run

properties:
  NAME:       'java'
  SRC_DIR:    'src'
  BUILD_DIR:  'build'
  CLASS_DIR:  '#{BUILD_DIR}/classes'
  MAIN_CLASS: 'test.Main'

targets:

  compile:
    doc: 'Compile java source files'
    steps:
    - mkdir: '#{CLASS_DIR}'
    - $: ['javac','-d', '#{CLASS_DIR}',
          '#{join(find(".", joinpath(SRC_DIR, "**/*.java")), " ")}']

  run:
    doc: 'Run java program'
    depends: compile
    steps:
    - $: ['java', '-cp', '#{CLASS_DIR}', '#{MAIN_CLASS}']

  clean:
    doc: 'Clean generated files'
    steps:
    - delete: '#{BUILD_DIR}'
