default: run

properties:
  BUILD_DIR: 'build'
  JAVA_SRC:  'src'
  JAVA_TST:  'test'
  CLASS_DIR: '#{BUILD_DIR}/classes'
  CLASS_TST: '#{BUILD_DIR}/test'
  JAVA_MAIN: 'casa.Main'

targets:

  compile:
    doc: 'Compile java source files'
    steps:
    - javac:  '**/*.java'
      source: '#{JAVA_SRC}'
      dest:   '#{CLASS_DIR}'

  java:
    doc: 'Run java program'
    depends: compile
    steps:
    - classpath: 'classpath'
      classes:   '#{CLASS_DIR}'
    - java: '#{JAVA_MAIN}'
      cp:   '#{classpath}'

  junit:
    doc: 'Run Junit tests'
    steps:
    - classpath: 'classpath'
      classes:   '#{CLASS_DIR}'
      depends:   'dependencies.yml'
      scope:     'test'
    - javac:  '**/*.java'
      source: '#{JAVA_TST}'
      dest:   '#{CLASS_TST}'

  clean:
    doc: 'Clean generated files'
    steps:
    - delete: '#{BUILD_DIR}'
