default: run

properties:
  NAME:       'java'
  SRC_DIR:    'src'
  TEST_DIR:   'test'
  BUILD_DIR:  'build'
  CLASS_DIR:  '#{BUILD_DIR}/classes'
  MAIN_CLASS: 'casa.Main'
  DEPENDENCIES:
  - group:    junit
    artifact: junit
    version:  4.12

targets:

  compile:
    doc: 'Compile java source files'
    steps:
    - javac:  '**/*.java'
      source: '#{SRC_DIR}'
      dest:   '#{CLASS_DIR}'

  run:
    doc: 'Run java program'
    depends: compile
    steps:
    - classpath: 'classpath'
      classes:   '#{CLASS_DIR}'
    - $: ['java', '-cp', '#{classpath}', '#{MAIN_CLASS}']

  clean:
    doc: 'Clean generated files'
    steps:
    - delete: '#{BUILD_DIR}'
